image: openjdk:8

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - build/
    - .gradlew/

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - publish

compile:
  stage: build
  script: ./gradlew build

documentation:
  stage: build
  script: ./gradlew dokka

runTests:
  stage: test
  script: ./gradlew test

publishToPackages:
  stage: publish
  only:
    refs:
      - master
    changes:
      - src/main/**/*
      - build.gradle.kts
  script: ./gradlew publish