image: openjdk:8

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - build/
    - .gradle/

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - publish

compile:
  stage: build
  only:
    changes:
      - "src/main/**/*"
  script: ./gradlew build

documentation:
  stage: build
  only:
    changes:
      - "src/**/*"
  script: ./gradlew dokka

runTests:
  stage: test
  script: ./gradlew test

publishToPackages:
  stage: publish
  only:
    refs:
      - master
    changes:
      - "src/main/**/*"
      - build.gradle.kts
  except:
    - merge_requets
  script: ./gradlew publish